# Generated by Django 4.2.2 on 2024-09-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Юзер", "verbose_name_plural": "Юзеры"},
        ),
    ]
