# Generated by Django 5.0.7 on 2024-09-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="views",
            new_name="views_count",
        ),
        migrations.AlterField(
            model_name="material",
            name="slug",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
