# Generated by Django 5.0.7 on 2024-09-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_views_material_views_count_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Material",
            new_name="Blog",
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "блог", "verbose_name_plural": "блоги"},
        ),
    ]
