# Generated by Django 5.0.7 on 2024-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_created_at_alter_product_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="current_version",
            field=models.BooleanField(default=False, verbose_name="Tекущая версия"),
        ),
    ]
