# Generated by Django 4.2.2 on 2024-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_version_current_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
    ]
