# Generated by Django 4.2.2 on 2024-10-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_version_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="token",
        ),
    ]
