# Generated by Django 4.2.2 on 2024-10-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price", "category"],
                "permissions": [
                    ("set_published", "Can publish product"),
                    ("can_change_description", "Can change description"),
                    ("can_change_category", "Can change category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
